var menudata={children:[
{text:"Página principal",url:"index.html"},
{text:"Páginas relacionadas",url:"pages.html"},
{text:"Classes",url:"annotated.html",children:[
{text:"Lista de componentes",url:"annotated.html"},
{text:"Índice dos componentes",url:"classes.html"},
{text:"Hierarquia de classes",url:"inherits.html"},
{text:"Componentes membro",url:"functions.html",children:[
{text:"Tudo",url:"functions.html",children:[
{text:"a",url:"functions.html#index_a"},
{text:"b",url:"functions.html#index_b"},
{text:"c",url:"functions.html#index_c"},
{text:"d",url:"functions.html#index_d"},
{text:"e",url:"functions.html#index_e"},
{text:"g",url:"functions.html#index_g"},
{text:"i",url:"functions.html#index_i"},
{text:"m",url:"functions.html#index_m"},
{text:"n",url:"functions.html#index_n"},
{text:"o",url:"functions.html#index_o"},
{text:"p",url:"functions.html#index_p"},
{text:"r",url:"functions.html#index_r"},
{text:"s",url:"functions.html#index_s"},
{text:"t",url:"functions.html#index_t"},
{text:"w",url:"functions.html#index_w"},
{text:"~",url:"functions.html#index_0x7e"}]},
{text:"Funções",url:"functions_func.html",children:[
{text:"a",url:"functions_func.html#index_a"},
{text:"b",url:"functions_func.html#index_b"},
{text:"c",url:"functions_func.html#index_c"},
{text:"d",url:"functions_func.html#index_d"},
{text:"e",url:"functions_func.html#index_e"},
{text:"g",url:"functions_func.html#index_g"},
{text:"i",url:"functions_func.html#index_i"},
{text:"m",url:"functions_func.html#index_m"},
{text:"n",url:"functions_func.html#index_n"},
{text:"o",url:"functions_func.html#index_o"},
{text:"p",url:"functions_func.html#index_p"},
{text:"r",url:"functions_func.html#index_r"},
{text:"s",url:"functions_func.html#index_s"},
{text:"t",url:"functions_func.html#index_t"},
{text:"w",url:"functions_func.html#index_w"},
{text:"~",url:"functions_func.html#index_0x7e"}]},
{text:"Variáveis",url:"functions_vars.html"}]}]},
{text:"Ficheiros",url:"files.html",children:[
{text:"Lista de ficheiros",url:"files.html"},
{text:"Membros dos Ficheiros",url:"globals.html",children:[
{text:"Tudo",url:"globals.html"},
{text:"Funções",url:"globals_func.html"},
{text:"Variáveis",url:"globals_vars.html"},
{text:"Definições de tipos",url:"globals_type.html"},
{text:"Macros",url:"globals_defs.html"}]}]}]}
